const SUPABASE_URL=String(process.env.SUPABASE_URL||'https://exfxcgiuotraszeqefha.supabase.co').replace(/\/$/,'');
const key=()=>process.env.SUPABASE_SERVICE_ROLE_KEY;
async function sfetch(path,opts={}){const k=key();if(!k)throw new Error('SUPABASE_SERVICE_ROLE_KEY is not configured');return fetch(SUPABASE_URL+'/rest/v1/'+path,{...opts,headers:{apikey:k,Authorization:`Bearer ${k}`,'Content-Type':'application/json',...(opts.headers||{})}})}
const LOT_SECONDS=10,BONUS_SECONDS=10,SOLD_SECONDS=2,DAY_KEYS=['sun','mon','tue','wed','thu','fri','sat'];
function dayFromDescription(v){const m=String(v||'').match(/\[\[auction_day:(mon|tue|wed|thu|fri|sat|sun)\]\]/i);return m?m[1].toLowerCase():null}
function dubaiParts(){const now=new Date(), day=new Intl.DateTimeFormat('en-US',{timeZone:'Asia/Dubai',weekday:'short'}).format(now).toLowerCase().slice(0,3), hour=Number(new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Dubai',hour:'2-digit',hourCycle:'h23'}).format(now));return{day,hour}}
function scheduledStartIso(targetDay){const now=new Date(), today=dubaiParts().day, a=DAY_KEYS.indexOf(today),b=DAY_KEYS.indexOf(targetDay);let delta=(b-a+7)%7;if(delta===0&&dubaiParts().hour>=18)delta=0;const dubaiDate=new Date(now.getTime()+4*3600000);dubaiDate.setUTCDate(dubaiDate.getUTCDate()+delta);dubaiDate.setUTCHours(18,0,0,0);return new Date(dubaiDate.getTime()-4*3600000).toISOString()}
async function activeLots(){const r=await sfetch('auction_lots?status=in.(upcoming,live)&select=id,lot_number,starting_bid,status,description,sort_order&order=sort_order.asc,lot_number.asc');if(!r.ok)return[];const rows=await r.json()||[];const now=Date.now();return rows.filter(x=>{const m=String(x.description||'').match(/\[\[retry_after:([^\]]+)\]\]/);return !m||Date.parse(m[1])<=now})}
function chooseQueue(rows,today){const todayRows=rows.filter(x=>dayFromDescription(x.description)===today);if(todayRows.length)return{day:today,rows:todayRows.slice(0,50)};const start=DAY_KEYS.indexOf(today);for(let n=1;n<=7;n++){const d=DAY_KEYS[(start+n)%7],q=rows.filter(x=>dayFromDescription(x.description)===d);if(q.length)return{day:d,rows:q.slice(0,50)}}return{day:today,rows:[]}}
async function setLotStatus(lotNumber,status,now){return sfetch(`auction_lots?lot_number=eq.${Number(lotNumber)}`,{method:'PATCH',body:JSON.stringify({status,updated_at:now})})}
module.exports=async(req,res)=>{if(req.method!=='GET'&&req.method!=='POST')return res.status(405).json({error:'Method not allowed'});try{
 let r=await sfetch('auction_state?id=eq.1&select=*');let state=(await r.json())?.[0];if(!r.ok||!state)throw new Error('Auction state unavailable');
 const nowMs=Date.now(),nowIso=new Date(nowMs).toISOString(),started=Date.parse(state.phase_started_at||state.updated_at||nowIso),age=Math.max(0,(nowMs-started)/1000),phase=String(state.phase||'red').toLowerCase(),dp=dubaiParts();
 let all=await activeLots(), chosen=chooseQueue(all,dp.day), queue=chosen.rows, canStart=chosen.day===dp.day&&dp.hour>=18;
 const currentNo=Number(state.lot_id||0), currentSelected=queue.find(x=>Number(x.lot_number)===currentNo);let patch=null;
 // Before 18:00 Dubai time the first lot is visible for preview, but bidding remains locked.
 if(!canStart){const first=queue[0];if(first&&(state.status!=='waiting'||currentNo!==Number(first.lot_number))){patch={lot_id:Number(first.lot_number),current_bid:Number(first.starting_bid||0),phase:'wait',phase_started_at:nowIso,status:'waiting'};}else if(!first&&state.status!=='waiting'){patch={phase:'wait',phase_started_at:nowIso,status:'waiting'};}}
 else if(!currentSelected){if(state.status==='live'&&currentNo)await setLotStatus(currentNo,'upcoming',nowIso);all=await activeLots();chosen=chooseQueue(all,dp.day);queue=chosen.rows;const first=queue[0];if(first){await setLotStatus(first.lot_number,'live',nowIso);patch={lot_id:Number(first.lot_number),current_bid:Number(first.starting_bid||0),phase:'red',phase_started_at:nowIso,status:'live'};}else patch={phase:'wait',phase_started_at:nowIso,status:'waiting'};}
 else if(state.status==='waiting'){await setLotStatus(currentSelected.lot_number,'live',nowIso);patch={lot_id:Number(currentSelected.lot_number),current_bid:Number(currentSelected.starting_bid||0),phase:'red',phase_started_at:nowIso,status:'live'};}
 else if(state.status==='live'&&phase==='sold'&&age>=SOLD_SECONDS){let br=await sfetch(`auction_bids?lot_id=eq.${currentNo}&select=id&limit=1`),hasBid=br.ok&&((await br.json())||[]).length>0;if(hasBid){await setLotStatus(currentNo,'pending',nowIso);}else{let lr=await sfetch(`auction_lots?lot_number=eq.${currentNo}&select=id,description`),ll=(await lr.json())?.[0];if(ll){let d=String(ll.description||'').replace(/\n?\[\[retry_after:[^\]]+\]\]/g,'').replace(/\n?\[\[auction_day:(?:mon|tue|wed|thu|fri|sat|sun)\]\]/gi,'').trim();await sfetch(`auction_lots?id=eq.${encodeURIComponent(ll.id)}`,{method:'PATCH',body:JSON.stringify({status:'draft',description:d||null,updated_at:nowIso})});}}all=await activeLots();chosen=chooseQueue(all,dp.day);queue=chosen.rows.filter(x=>Number(x.lot_number)!==currentNo);const next=queue[0];if(next){await setLotStatus(next.lot_number,'live',nowIso);patch={lot_id:Number(next.lot_number),current_bid:Number(next.starting_bid||0),phase:'red',phase_started_at:nowIso,status:'live'};}else patch={phase:'wait',phase_started_at:nowIso,status:'waiting'};}
 else if(state.status==='live'&&!['bonus','green','sold','wait'].includes(phase)&&age>=LOT_SECONDS)patch={phase:'bonus',phase_started_at:nowIso,status:'live'};
 else if(state.status==='live'&&['bonus','green'].includes(phase)&&age>=BONUS_SECONDS)patch={phase:'sold',phase_started_at:nowIso,status:'live'};
 if(patch){const expected=encodeURIComponent(state.phase_started_at||''),q=`auction_state?id=eq.1&phase_started_at=eq.${expected}&phase=eq.${encodeURIComponent(state.phase||'')}`;r=await sfetch(q,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify({...patch,updated_at:nowIso})});const changed=await r.json();if(r.ok&&changed?.length)state=changed[0];else{r=await sfetch('auction_state?id=eq.1&select=*');state=(await r.json())?.[0]||state;}}
 const lotId=Number(state.lot_id||0);r=await sfetch(`auction_bids?lot_id=eq.${lotId}&select=user_id,username,country,amount,created_at,id&order=id.desc&limit=4`);const bids=await r.json();
 let lot=null;if(lotId){const lr=await sfetch(`auction_lots?lot_number=eq.${lotId}&select=*,auction_lot_images(id,image_url,is_primary,sort_order)`);const rows=await lr.json();if(lr.ok&&rows?.[0]){lot=rows[0];const images=(lot.auction_lot_images||[]).sort((a,b)=>(a.sort_order||0)-(b.sort_order||0));delete lot.auction_lot_images;lot.images=images;lot.primary_image=(images.find(x=>x.is_primary)||images[0])?.image_url||null;}}
 const sr=await sfetch('auction_lots?select=lot_number,status');const statusRows=sr.ok?await sr.json():[];const lotStatuses=Object.fromEntries((statusRows||[]).map(x=>[String(x.lot_number),x.status]));
 all=await activeLots();chosen=chooseQueue(all,dp.day);queue=chosen.rows;
 res.setHeader('Cache-Control','no-store, max-age=0');res.status(200).json({serverNow:nowIso,today:chosen.day,todayQueue:queue.map(x=>Number(x.lot_number)),scheduledStart:'18:00',startAt:scheduledStartIso(chosen.day),canBid:chosen.day===dp.day&&dp.hour>=18,state,bids:Array.isArray(bids)?bids:[],lot,lotStatuses});
 }catch(e){res.status(500).json({error:e.message});}}
