const crypto=require('crypto');
function verify(initData,token){const p=new URLSearchParams(String(initData||'')),hash=p.get('hash');if(!token||!hash)return null;p.delete('hash');const data=[...p].sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>`${k}=${v}`).join('\n'),secret=crypto.createHmac('sha256','WebAppData').update(token).digest(),calc=crypto.createHmac('sha256',secret).update(data).digest('hex');try{const expected=Buffer.from(calc,'hex'),actual=Buffer.from(hash,'hex');if(expected.length!==actual.length||!crypto.timingSafeEqual(expected,actual))return null;const user=JSON.parse(p.get('user')||'null');return user?.id?user:null}catch{return null}}
const base=()=>String(process.env.SUPABASE_URL||'https://exfxcgiuotraszeqefha.supabase.co').replace(/\/$/,'');
async function sf(path,options={}){const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!key)throw Error('Server not configured');return fetch(`${base()}/rest/v1/${path}`,{...options,headers:{apikey:key,Authorization:`Bearer ${key}`,'Content-Type':'application/json',...(options.headers||{})}})}
const optionalFields='email,phone,phone_country,avatar_url,language';
const languages=new Set(['ru','en','ar']);
function editableProfile(body={}){const patch={};if(Object.hasOwn(body,'firstName')){const name=String(body.firstName||'').trim().slice(0,80);if(!name)throw Error('Укажите имя');patch.first_name=name}if(Object.hasOwn(body,'phone')){const phone=String(body.phone||'').replace(/[\s()-]/g,'');if(phone&&!/^\+[1-9]\d{6,14}$/.test(phone))throw Error('Введите телефон в международном формате');patch.phone=phone||null}if(Object.hasOwn(body,'phoneCountry')){const country=String(body.phoneCountry||'').toUpperCase();if(!/^[A-Z]{2}$/.test(country))throw Error('Выберите страну');patch.phone_country=country}if(Object.hasOwn(body,'email')){const email=String(body.email||'').trim().toLowerCase();if(email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw Error('Некорректный email');patch.email=email||null}if(Object.hasOwn(body,'language')){const language=String(body.language||'').toLowerCase();if(!languages.has(language))throw Error('Некорректный язык');patch.language=language}if(body.avatarUrl){const avatar=String(body.avatarUrl);if(!/^data:image\/(jpeg|png|webp);base64,/.test(avatar))throw Error('Некорректная фотография');if(avatar.length>700000)throw Error('Фотография слишком большая');patch.avatar_url=avatar}if(!Object.keys(patch).length)throw Error('Нет данных для сохранения');patch.updated_at=new Date().toISOString();return patch}
module.exports=async(req,res)=>{if(req.method!=='POST')return res.status(405).json({error:'Method not allowed'});const user=verify(req.body?.initData,process.env.TELEGRAM_BOT_TOKEN);if(!user)return res.status(401).json({error:'Telegram authentication required'});try{if(req.body?.readOnly===true){const r=await sf(`auction_users?telegram_id=eq.${encodeURIComponent(String(user.id))}&select=${optionalFields}&limit=1`),rows=await r.json();if(!r.ok)throw Error(rows?.message||'Profile details unavailable');return res.status(200).json({profile:rows?.[0]||{}})}const patch=editableProfile(req.body),r=await sf(`auction_users?telegram_id=eq.${encodeURIComponent(String(user.id))}`,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify(patch)}),rows=await r.json();if(!r.ok)throw Error(rows?.message||'Profile update failed');if(!rows?.[0])return res.status(404).json({error:'Профиль не найден'});const profile={};for(const field of ['first_name',...optionalFields.split(',')])profile[field]=rows[0][field];return res.status(200).json({profile})}catch(e){const invalid=['Укажите имя','Введите телефон','Некорректный','Выберите страну','Фотография слишком','Нет данных'].some(x=>e.message.startsWith(x));return res.status(invalid?(e.message.startsWith('Фотография слишком')?413:400):500).json({error:e.message})}};
module.exports.editableProfile=editableProfile;
