const crypto=require('crypto');
function verify(initData,token){const p=new URLSearchParams(String(initData||'')),hash=p.get('hash');if(!token||!hash)return null;p.delete('hash');const data=[...p].sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>`${k}=${v}`).join('\n'),secret=crypto.createHmac('sha256','WebAppData').update(token).digest(),calc=crypto.createHmac('sha256',secret).update(data).digest('hex');try{if(!crypto.timingSafeEqual(Buffer.from(calc,'hex'),Buffer.from(hash,'hex')))return null;return JSON.parse(p.get('user'))}catch{return null}}
const base=()=>String(process.env.SUPABASE_URL||'https://exfxcgiuotraszeqefha.supabase.co').replace(/\/$/,'');
async function sf(path,options={}){const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!key)throw Error('Server not configured');return fetch(`${base()}/rest/v1/${path}`,{...options,headers:{apikey:key,Authorization:`Bearer ${key}`,'Content-Type':'application/json',...(options.headers||{})}})}
const fields='telegram_id,username,first_name,last_name,email,phone,phone_country,avatar_url,country,deposit_amount,bid_limit,account_status,created_at,is_admin,residential_country,residential_city,residential_region,residential_address,postal_code,mailing_address,mailing_same_as_residential';
const text=(value,max=240)=>String(value||'').trim().slice(0,max);
function profilePatch(body={}){const patch={};if(Object.hasOwn(body,'email')){const email=text(body.email,160).toLowerCase();if(email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw Error('Некорректный email');patch.email=email||null}if(Object.hasOwn(body,'phone')){const phone=text(body.phone,32).replace(/[\s()-]/g,'');if(phone&&!/^\+[1-9]\d{6,14}$/.test(phone))throw Error('Введите телефон в международном формате');const country=text(body.phoneCountry,2).toUpperCase();if(phone&&!/^[A-Z]{2}$/.test(country))throw Error('Выберите страну');patch.phone=phone||null;patch.phone_country=country||null}if(Object.hasOwn(body,'fullName')){const full=text(body.fullName,160),parts=full.split(/\s+/).filter(Boolean);patch.first_name=parts.shift()||null;patch.last_name=parts.join(' ')||null}if(Object.hasOwn(body,'residentialAddress')){patch.residential_country=text(body.residentialCountry,80)||null;patch.residential_city=text(body.residentialCity,100)||null;patch.residential_region=text(body.residentialRegion,100)||null;patch.residential_address=text(body.residentialAddress,240)||null}if(Object.hasOwn(body,'postalCode'))patch.postal_code=text(body.postalCode,32)||null;if(Object.hasOwn(body,'mailingAddress')){const same=body.mailingSame===true;patch.mailing_same_as_residential=same;patch.mailing_address=same?null:text(body.mailingAddress,300)||null}if(Object.hasOwn(body,'firstName')){patch.first_name=text(body.firstName,80)||null;patch.last_name=text(body.lastName,80)||null}if(body.avatarUrl){const avatar=String(body.avatarUrl);if(!/^data:image\/(jpeg|png|webp);base64,/.test(avatar))throw Error('Некорректная фотография');if(avatar.length>700000)throw Error('Фотография слишком большая');patch.avatar_url=avatar}if(!Object.keys(patch).length)throw Error('Нет данных для сохранения');patch.updated_at=new Date().toISOString();return patch}
module.exports=async(req,res)=>{if(!['GET','POST'].includes(req.method))return res.status(405).json({error:'Method not allowed'});const user=verify(req.method==='POST'?req.body?.initData:req.headers['x-telegram-init-data'],process.env.TELEGRAM_BOT_TOKEN);if(!user)return res.status(401).json({error:'Telegram authentication required'});try{if(req.method==='GET'){const r=await sf(`auction_users?telegram_id=eq.${encodeURIComponent(String(user.id))}&select=${fields}&limit=1`),rows=await r.json();if(!r.ok)throw Error(rows?.message||'Profile unavailable');return res.status(200).json({profile:rows?.[0]||null})}const patch=profilePatch(req.body||{}),r=await sf(`auction_users?telegram_id=eq.${encodeURIComponent(String(user.id))}`,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify(patch)}),rows=await r.json();if(!r.ok)throw Error(rows?.message||'Profile update failed');if(!rows?.[0])return res.status(404).json({error:'Профиль не найден'});return res.status(200).json({profile:rows[0]})}catch(e){const invalid=['Некорректный','Введите телефон','Выберите страну','Фотография слишком','Нет данных'].some(x=>e.message.startsWith(x));return res.status(invalid?400:500).json({error:e.message})}};
module.exports.profilePatch=profilePatch;
